#! /bin/zsh

say -i "Installing in 3, 2, 1"
say -i "Installing now"

if ./gradlew installDebug; then
    say -i "Installation complete"
else
    say -i "Oepsie woepsie de install es stukkie wukkie"
fi
